import {
    Bell,
    BookOpen,
    Bot,
    ClipboardCheck,
    FileText,
    LibraryBig,
    Megaphone,
    Newspaper,
    NotepadText,
    Target,
    Trophy,
  } from "lucide-react";
  
  export const learningTools = [
    {
      title: "Current Affairs",
      subtitle: "Daily updates",
      href: "/kerala-psc-coaching/current-affairs",
      icon: Newspaper,
      iconColor: "text-[#ec2384]",
      iconBg: "bg-[#ffe1f1]",
    },
    {
      title: "Mock Tests",
      subtitle: "Practice now",
      href: "/kerala-psc-coaching/mock-tests",
      icon: ClipboardCheck,
      iconColor: "text-[#087bea]",
      iconBg: "bg-[#dcefff]",
    },
    {
      title: "Previous Questions",
      subtitle: "Question bank",
      href: "/kerala-psc-coaching/previous-questions",
      icon: NotepadText,
      iconColor: "text-[#0dac77]",
      iconBg: "bg-[#d9f7eb]",
    },
    {
      title: "Exam Syllabus",
      subtitle: "Detailed syllabus",
      href: "/kerala-psc-coaching/exam-syllabus",
      icon: BookOpen,
      iconColor: "text-[#6131e8]",
      iconBg: "bg-[#ebe4ff]",
    },
    {
      title: "SCERT Tests",
      subtitle: "Textbook based",
      href: "/kerala-psc-coaching/scert-tests",
      icon: LibraryBig,
      iconColor: "text-[#f26522]",
      iconBg: "bg-[#fff0df]",
    },
    {
      title: "PSC Alerts",
      subtitle: "Notifications",
      href: "/kerala-psc-coaching/psc-notifications",
      icon: Bell,
      iconColor: "text-[#1688ed]",
      iconBg: "bg-[#dff1ff]",
    },
    {
      title: "PSC Bulletin",
      subtitle: "Official updates",
      href: "/kerala-psc-coaching/psc-bulletin-ca",
      icon: Megaphone,
      iconColor: "text-[#ef2786]",
      iconBg: "bg-[#ffe2f1]",
    },
    {
      title: "Topic / Subtopic Exams",
      subtitle: "Practice topic-wise",
      href: "/kerala-psc-coaching/topic-wise-exams",
      icon: Target,
      iconColor: "text-[#f3195d]",
      iconBg: "bg-[#ffe3eb]",
    },
    {
      title: "Topicwise Statement Type",
      subtitle: "Subject wise",
      href: "/kerala-psc-coaching/statement-type-exams",
      icon: NotepadText,
      iconColor: "text-[#5933eb]",
      iconBg: "bg-[#e9e4ff]",
    },
    {
      title: "PDF",
      subtitle: "Study materials",
      href: "/kerala-psc-coaching/study-materials",
      icon: FileText,
      iconColor: "text-[#ed245b]",
      iconBg: "bg-[#ffe2ea]",
    },
    {
      title: "Monthly Quiz",
      subtitle: "Test your knowledge",
      href: "/kerala-psc-coaching/current-affairs-quiz",
      icon: Trophy,
      iconColor: "text-[#f4a000]",
      iconBg: "bg-[#fff0d7]",
    },
    {
      title: "AI Videos",
      subtitle: "Learn with AI",
      href: "/kerala-psc-coaching/ai-videos",
      icon: Bot,
      iconColor: "text-[#147be8]",
      iconBg: "bg-[#dcefff]",
    },
  ];